name: Daily Inventory Check

on:
  schedule:
    # 21:00 UTC entspricht 22:00 CET
    - cron: '0 21 * * *'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install @supabase/supabase-js node-fetch

      - name: Run daily inventory check
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          FORMSPREE_ENDPOINT: ${{ secrets.FORMSPREE_ENDPOINT }}
        run: |
          node scripts/checkInventory.js
